# Site
repository: sproogen/resume-theme
favicon: images/yinyang_blue.ico

# Personal info
name: Keenan Thompson
title: Software Engineer
email: keenan.thompson67@gmail.com
# website:

# Social links
# twitter_username:
github_username: kthom1
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username:
linkedin_username: keenanthompson
# pinterest_username: jekyll
# youtube_username:
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm an American software engineer who speaks Japanese and has extensive experience working abroad.
  In China I worked at a relatively small company with only a few dozen employees, and in Japan I worked at one of the largest companies in the country.
  I have experience working remotely, and I'm a strong communicator.

  Now located in: <mark>Taipei, Taiwan</mark>

  I am most skilled in: <code>Ruby on Rails</code>, <code>React</code>, <code>React-Native</code>, and <code>Express</code>

  Now I'm learning: <code>Flutter</code>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Awards and Certifications
more_content: | # this will include new lines to allow paragraphs
  <mark>Awards</mark>
  - Glenwood G. Clark Fiction Prize – 1st Place (The College of William and Mary Alumni Association)
  - Tiberius Gracchus Jones Nonfiction Prize – 2nd Place (The College of William and Mary Alumni Association)

  <mark>Certifications</mark>
  - Japanese Language Proficiency Test - N2 (December 2013)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
